spring:
  cloud:
    gateway:
      discovery:
        server:
          webflux:
      routes:
        - id: weather-route
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/api/locations/**,/api/weathers/**,/api/forecast/**,/api/test/**

        - id: iot-route
          uri: lb://IOT-SERVICE
          predicates:
            - Path=/api/waters/**,/api/sensors/**,/api/reading/**,/api/environment/**

        - id: data-route
          uri: lb://DATA-AGGREGATION-SERVICE
          predicates:
              - Path=/api/aggregate/**